"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { createClient } from "@/lib/supabase/client";

// Landing point after clicking the invite-email link (Batch 23/24).
//
// IMPORTANT — why this page does its own token parsing instead of going
// through /auth/callback: Supabase's invite links (as generated by
// admin.auth.admin.inviteUserByEmail on this project) return the session
// as #access_token=...&refresh_token=...  in the URL FRAGMENT, not as a
// ?code= query param. Fragments are never sent to the server — a Route
// Handler like /auth/callback physically cannot see them, no matter what
// "next" redirect target it's given. That's exactly what was happening
// before Batch 24: the browser hit /auth/callback with no usable code,
// the route bailed out to /login?error=auth_callback_failed, and Chrome
// just carried the leftover, now-useless fragment along for the ride —
// which is the stray #access_token=... that showed up on the login page
// URL. The fix is to send the invite link straight here, to a page that
// runs in the browser and can read window.location.hash directly.
export default function SetPasswordPage() {
  const router = useRouter();
  const supabase = createClient();

  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [checkingSession, setCheckingSession] = useState(true);
  const [sessionReady, setSessionReady] = useState(false);

  useEffect(() => {
    async function establishSession() {
      // The Supabase browser client (detectSessionInUrl) usually parses
      // the hash automatically on load, but that depends on timing
      // during Next's client hydration — so we also parse it by hand as
      // a reliable fallback rather than trusting auto-detection alone.
      const hash = window.location.hash?.startsWith("#")
        ? window.location.hash.slice(1)
        : "";
      const hashParams = new URLSearchParams(hash);
      const accessToken = hashParams.get("access_token");
      const refreshToken = hashParams.get("refresh_token");

      if (accessToken && refreshToken) {
        const { error: sessionError } = await supabase.auth.setSession({
          access_token: accessToken,
          refresh_token: refreshToken,
        });
        if (!sessionError) {
          // Clean the sensitive tokens out of the visible URL/history.
          window.history.replaceState(null, "", window.location.pathname);
          setSessionReady(true);
          setCheckingSession(false);
          return;
        }
      }

      // No usable hash tokens — maybe the person already has a session
      // from an earlier visit to this same link, or the link is stale.
      const { data } = await supabase.auth.getSession();
      setSessionReady(!!data.session);
      setCheckingSession(false);
    }
    establishSession();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);

    if (password.length < 8) {
      setError("密碼至少需要 8 個字元。");
      return;
    }
    if (password !== confirm) {
      setError("兩次輸入的密碼不一致。");
      return;
    }

    setLoading(true);
    const { error: updateError } = await supabase.auth.updateUser({ password });

    if (updateError) {
      setError("設定密碼失敗，請重新點選邀請信中的連結，或聯絡您的機構顧問。");
      setLoading(false);
      return;
    }

    router.push("/dashboard");
    router.refresh();
  }

  return (
    <main className="min-h-screen flex flex-col items-center justify-center gap-8 px-6">
      <Image
        src="/logo.png"
        alt="Native English"
        width={1389}
        height={288}
        priority
        className="h-auto w-[200px]"
      />

      <div className="w-full max-w-sm rounded border border-line bg-surface p-6 shadow-card">
        {checkingSession ? (
          <p className="text-sm text-slate">正在驗證邀請連結…</p>
        ) : !sessionReady ? (
          <>
            <h1 className="font-display text-lg font-bold text-ink mb-1">連結已失效</h1>
            <p className="text-sm text-slate">
              這個邀請連結無法使用，可能已經過期或已經被使用過。請聯絡您的機構顧問，請他們重新為您建立帳號或重新寄送邀請信。
            </p>
          </>
        ) : (
          <form onSubmit={handleSubmit}>
            <h1 className="font-display text-lg font-bold text-ink mb-1">設定密碼</h1>
            <p className="text-sm text-slate mb-6">
              您的機構已經為您建立帳號，請設定一組密碼以完成登入。
            </p>

            <label className="block text-sm font-medium text-ink mb-1" htmlFor="password">
              新密碼
            </label>
            <input
              id="password"
              type="password"
              required
              minLength={8}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full rounded border border-line px-3 py-2 mb-4 text-sm focus:border-brand outline-none"
              placeholder="至少 8 個字元"
            />

            <label className="block text-sm font-medium text-ink mb-1" htmlFor="confirm">
              再次輸入密碼
            </label>
            <input
              id="confirm"
              type="password"
              required
              minLength={8}
              value={confirm}
              onChange={(e) => setConfirm(e.target.value)}
              className="w-full rounded border border-line px-3 py-2 mb-4 text-sm focus:border-brand outline-none"
              placeholder="••••••••"
            />

            {error && (
              <p className="text-sm text-danger mb-4" role="alert">
                {error}
              </p>
            )}

            <button
              type="submit"
              disabled={loading}
              className="w-full rounded bg-ink py-2.5 text-sm font-semibold text-white disabled:opacity-60"
            >
              {loading ? "設定中…" : "設定密碼並登入"}
            </button>
          </form>
        )}
      </div>
    </main>
  );
}

